---
sidebar: sidebar 
permalink: trident-docker/stor-config.html 
keywords: deploy, trident, docker, trident for docker, nfs, iscsi, protocol, nfs protocol, iscsi protocol, configure host, host config, storage config, options, variables, ontap, element, storage pool, cvs, cvs-performance, service type, service level, cloud volumes service, cloud volumes 
summary: Sehen Sie sich die Konfigurationsoptionen der Astra Trident Konfigurationen an. 
---
= Optionen für die Storage-Konfiguration
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sehen Sie sich die Konfigurationsoptionen der Astra Trident Konfigurationen an.



== Globale Konfigurationsoptionen

Diese Konfigurationsoptionen sind für alle Astra Trident Konfigurationen anwendbar, unabhängig von der genutzten Storage-Plattform.

[cols="3*"]
|===
| Option | Beschreibung | Beispiel 


| `version`  a| 
Versionsnummer der Konfigurationsdatei
 a| 
`1`



| `storageDriverName`  a| 
Name des Speichertreibers
 a| 
`ontap-nas`, `ontap-san`, `ontap-nas-economy`,
`ontap-nas-flexgroup`, `solidfire-san`



| `storagePrefix`  a| 
Optionales Präfix für Volume-Namen Standard: `netappdvp_`.
 a| 
`staging_`



| `limitVolumeSize`  a| 
Optionale Einschränkung von Volume-Größen. Standard: „“ (nicht erzwungen)
 a| 
`10g`

|===

TIP: Verwenden Sie (einschließlich der Standardeinstellung) keine `storagePrefix` Back-Ends für Elemente. Standardmäßig ignoriert der `solidfire-san` Treiber diese Einstellung und verwendet kein Präfix. Wir empfehlen die Verwendung einer bestimmten TenantID für die Docker Volume-Zuordnung oder die Verwendung der Attributdaten, die mit der Docker-Version, den Treiber-Informationen und dem Raw-Namen aus Docker gefüllt sind, in Fällen, in denen Namensnennung verwendet wurde.

Es stehen Standardoptionen zur Verfügung, damit Sie sie nicht für jedes erstellte Volume angeben müssen. Die `size` Option ist für alle Controller-Typen verfügbar. Im Abschnitt zur ONTAP-Konfiguration finden Sie ein Beispiel dafür, wie Sie die Standard-Volume-Größe festlegen.

[cols="3*"]
|===
| Option | Beschreibung | Beispiel 


| `size`  a| 
Optionale Standardgröße für neue Volumes. Standard: `1G`
 a| 
`10G`

|===


== ONTAP-Konfiguration

Zusätzlich zu den oben genannten globalen Konfigurationswerten stehen bei Verwendung von ONTAP folgende Optionen auf oberster Ebene zur Verfügung.

[cols="3*"]
|===
| Option | Beschreibung | Beispiel 


| `managementLIF`  a| 
IP-Adresse des ONTAP Management LIF. Sie können einen vollqualifizierten Domänennamen (FQDN) angeben.
 a| 
`10.0.0.1`



| `dataLIF`  a| 
IP-Adresse des LIF-Protokolls.

*ONTAP NAS Treiber*: Wir empfehlen die Angabe `dataLIF`. Falls nicht vorgesehen, ruft Astra Trident Daten-LIFs von der SVM ab. Sie können einen vollständig qualifizierten Domänennamen (FQDN) angeben, der für die NFS-Mount-Vorgänge verwendet werden soll. Damit können Sie ein Round-Robin-DNS zum Load-Balancing über mehrere Daten-LIFs erstellen.

*ONTAP-SAN-Treiber*: Geben Sie nicht für iSCSI an. Astra Trident verwendet link:https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html["ONTAP selektive LUN-Zuordnung"^] zur Erkennung der iSCI LIFs, die für eine Multi-Path-Session erforderlich sind. Eine Warnung wird erzeugt, wenn `dataLIF` explizit definiert ist.
 a| 
`10.0.0.2`



| `svm`  a| 
Storage Virtual Machine zu verwenden (erforderlich, falls Management LIF eine Cluster-LIF ist)
 a| 
`svm_nfs`



| `username`  a| 
Benutzername zur Verbindung mit dem Speichergerät
 a| 
`vsadmin`



| `password`  a| 
Passwort für die Verbindung mit dem Speichergerät
 a| 
`secret`



| `aggregate`  a| 
Aggregat für die Bereitstellung (optional, wenn eingestellt, muss der SVM zugewiesen werden) Für den `ontap-nas-flexgroup` Treiber wird diese Option ignoriert. Alle der SVM zugewiesenen Aggregate werden zur Bereitstellung eines FlexGroup Volumes verwendet.
 a| 
`aggr1`



| `limitAggregateUsage`  a| 
Optionale, fail-Provisioning-Funktion, wenn die Nutzung über diesem Prozentsatz liegt
 a| 
`75%`



| `nfsMountOptions`  a| 
Feingranulare Steuerung der NFS-Mount-Optionen; standardmäßig „-o nfsvers=3“. *Nur verfügbar für die `ontap-nas` und `ontap-nas-economy` Fahrer*. https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["Siehe Informationen zur NFS-Host-Konfiguration hier"^].
 a| 
`-o nfsvers=4`



| `igroupName`  a| 
Astra Trident erstellt und managt pro Node `igroups` wie `netappdvp`.

Dieser Wert kann nicht geändert oder weggelassen werden.

*Nur für den Fahrer verfügbar `ontap-san`*.
 a| 
`netappdvp`



| `limitVolumeSize`  a| 
Maximale anforderbare Volume-Größe.
 a| 
`300g`



| `qtreesPerFlexvol`  a| 
Maximale Anzahl der qtrees pro FlexVol, die im Bereich [50, 300] liegen müssen, die Standardeinstellung ist 200.

*Für den `ontap-nas-economy` Treiber ermöglicht diese Option die Anpassung der maximalen Anzahl von qtrees pro FlexVol*.
 a| 
`300`



| `sanType` | *Nur für Treiber unterstützt `ontap-san`.* Verwenden Sie, um für iSCSI oder `nvme` für NVMe/TCP auszuwählen `iscsi`. | `iscsi` Falls leer 


| `limitVolumePoolSize` | * `ontap-san-economy` `ontap-san-economy`Nur für und Treiber unterstützt.* Begrenzung der FlexVol-Größe bei den wirtschaftlichen Faktoren ONTAP ONTAP-nas und ONTAP-SAN  a| 
`300g`

|===
Es stehen Standardoptionen zur Verfügung, um zu vermeiden, dass sie auf jedem von Ihnen erstellten Volume angegeben werden müssen:

[cols="1,3,2"]
|===
| Option | Beschreibung | Beispiel 


| `spaceReserve`  a| 
Modus für Speicherplatzreservierung `none` (Thin Provisioning) oder (Thick) `volume`
 a| 
`none`



| `snapshotPolicy`  a| 
Zu verwendende Snapshot-Richtlinie, Standard ist `none`
 a| 
`none`



| `snapshotReserve`  a| 
Der Prozentsatz der Snapshot-Reserve ist standardmäßig „“, um den ONTAP-Standardwert zu akzeptieren
 a| 
`10`



| `splitOnClone`  a| 
Teilen Sie einen Klon bei der Erstellung von seinem übergeordneten Element auf. Dies ist standardmäßig der Standardwert `false`
 a| 
`false`



| `encryption`  a| 
Aktiviert NetApp Volume Encryption (NVE) auf dem neuen Volume; Standardeinstellung ist `false`. NVE muss im Cluster lizenziert und aktiviert sein, damit diese Option verwendet werden kann.

Wenn NAE auf dem Backend aktiviert ist, wird jedes im Astra Trident bereitgestellte Volume NAE aktiviert.

Weitere Informationen finden Sie unter link:../trident-reco/security-reco.html["Astra Trident arbeitet mit NVE und NAE zusammen"].
 a| 
Richtig



| `unixPermissions`  a| 
NAS-Option für bereitgestellte NFS-Volumes, standardmäßig auf `777`
 a| 
`777`



| `snapshotDir`  a| 
NAS-Option für den Zugriff auf das `.snapshot` Verzeichnis, standardmäßig auf `false`
 a| 
`true`



| `exportPolicy`  a| 
NAS-Option für die zu verwendende NFS-Exportrichtlinie, standardmäßig auf `default`
 a| 
`default`



| `securityStyle`  a| 
NAS-Option für Zugriff auf das bereitgestellte NFS-Volume.

NFS-Unterstützung `mixed` und `unix` -Sicherheitsstile. Der Standardwert ist `unix`.
 a| 
`unix`



| `fileSystemType`  a| 
SAN-Option zum Auswählen des Dateisystemtyps, standardmäßig auf `ext4`
 a| 
`xfs`



| `tieringPolicy`  a| 
Zu verwendende Tiering Policy, Standard ist `none`; `snapshot-only` für pre-ONTAP 9.5 SVM-DR Konfiguration
 a| 
`none`

|===


=== Skalierungsoptionen

Die `ontap-nas` Treiber und `ontap-san` erstellen eine ONTAP FlexVol für jedes Docker Volume. ONTAP unterstützt bis zu 1000 FlexVols pro Cluster Node mit einem Cluster maximal 12,000 FlexVols. Wenn die Anforderungen für Docker Volumes dieser Einschränkung entsprechen, ist der `ontap-nas` Treiber aufgrund der zusätzlichen Funktionen von FlexVols wie granulare Docker Volume-Snapshots und Klonen die bevorzugte NAS-Lösung.

Wenn Sie mehr Docker Volumes benötigen, als durch die FlexVol-Beschränkungen unterstützt werden können, wählen Sie den oder den `ontap-san-economy` Treiber aus `ontap-nas-economy`.

Der `ontap-nas-economy` Treiber erstellt Docker Volumes als ONTAP qtrees innerhalb eines Pools von automatisch gemanagten FlexVols. Qtrees bieten eine wesentlich größere Skalierung – bis zu 100,000 pro Cluster-Node und 2,400,000 pro Cluster – zu Lasten einiger Funktionen.  `ontap-nas-economy`Snapshots oder Klonen mit granularem Docker Volume werden vom Treiber nicht unterstützt.


NOTE: Der `ontap-nas-economy` Treiber wird derzeit in Docker Swarm nicht unterstützt, da Swarm die Volume-Erstellung nicht über mehrere Nodes hinweg orchestriert.

Der `ontap-san-economy` Treiber erstellt Docker Volumes als ONTAP LUNs in einem gemeinsamen Pool von automatisch gemanagten FlexVols. Somit ist jede FlexVol nicht auf nur eine LUN beschränkt und bietet eine bessere Skalierbarkeit für SAN-Workloads. Je nach Storage Array unterstützt ONTAP bis zu 16384 LUNs pro Cluster. Da es sich bei den Volumes um LUNs handelt, unterstützt dieser Treiber granulare Docker Snapshots und Klone.

Wählen Sie den `ontap-nas-flexgroup` Treiber, um die Parallelität zu einem einzelnen Volume zu erhöhen, das bis in den Petabyte-Bereich mit Milliarden von Dateien anwachsen kann. Zu den idealen Anwendungsfällen für FlexGroups gehören KI/ML/DL, Big Data und Analysen, Softwareentwicklung, Streaming, Datei-Repositorys und so weiter. Trident verwendet alle Aggregate, die einer SVM bei der Bereitstellung eines FlexGroup-Volumes zugewiesen sind. Die Unterstützung von FlexGroup in Trident muss darüber hinaus Folgendes beachtet werden:

* ONTAP Version 9.2 oder höher erforderlich.
* Ab diesem Text unterstützt FlexGroups nur NFS v3.
* Empfohlen, die 64-Bit-NFSv3-IDs für die SVM zu aktivieren.
* Die empfohlene Mindestgröße für FlexGroup-Mitglieder/Volumes beträgt 100 gib.
* Klonen wird für FlexGroup Volumes nicht unterstützt.


Informationen zu FlexGroups und Workloads, die für FlexGroups geeignet sind, finden Sie unter https://www.netapp.com/pdf.html?item=/media/12385-tr4571pdf.pdf["NetApp FlexGroup Volume Best Practices und Implementierungsleitfaden"^].

Um erweiterte Funktionen und umfassende Skalierbarkeit in derselben Umgebung zu erhalten, können Sie mehrere Instanzen des Docker Volume Plug-ins ausführen, wobei eine davon und eine andere `ontap-nas-economy` verwendet `ontap-nas` wird.



=== Beispiel für ONTAP-Konfigurationsdateien

.NFS-Beispiel für <code> ONTAP-</code>-Treiber
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "defaults": {
      "size": "10G",
      "spaceReserve": "none",
      "exportPolicy": "default"
    }
}
----
====
.NFS-Beispiel für <code> ONTAP-nas-FlexGroup </code>-Treiber
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas-flexgroup",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "defaults": {
      "size": "100G",
      "spaceReserve": "none",
      "exportPolicy": "default"
    }
}
----
====
.NFS Beispiel für </code>-Treiber für <code> ONTAP-nas-economl
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas-economy",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1"
}
----
====
.ISCSI-Beispiel für <code> ONTAP-</code>-Treiber
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-san",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.3",
    "svm": "svm_iscsi",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "igroupName": "netappdvp"
}
----
====
.NFS Beispiel für </code>-Treiber für <code> ONTAP-san-economl
[%collapsible]
====
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-san-economy",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.3",
    "svm": "svm_iscsi_eco",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "igroupName": "netappdvp"
}
----
====
.NVMe/TCP – Beispiel für einen <code> ONTAP-</code>-Treiber
[%collapsible]
====
[listing]
----
{
  "version": 1,
  "backendName": "NVMeBackend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "svm": "svm_nvme",
  "username":"vsadmin",
  "password":"password",
  "sanType": "nvme",
  "useREST": true
}
----
====


== Konfiguration von Element Software

Zusätzlich zu den Werten einer globalen Konfiguration sind bei Verwendung von Element Software (NetApp HCI/SolidFire) diese Optionen verfügbar.

[cols="3*"]
|===
| Option | Beschreibung | Beispiel 


| `Endpoint`  a| 
\Https://<login>:<password>@<mvip>/json-rpc/<element-version>
 a| 
\https://admin:admin@192.168.160.3/json-rpc/8.0



| `SVIP`  a| 
ISCSI-IP-Adresse und -Port
 a| 
10.0.0.7:3260 Uhr



| `TenantName`  a| 
SolidFireF Mandanten zu verwenden (erstellt, falls nicht gefunden)
 a| 
`docker`



| `InitiatorIFace`  a| 
Geben Sie die Schnittstelle an, wenn der iSCSI-Datenverkehr auf eine nicht-Standardschnittstelle beschränkt wird
 a| 
`default`



| `Types`  a| 
QoS-Spezifikationen
 a| 
Siehe das Beispiel unten



| `LegacyNamePrefix`  a| 
Präfix für aktualisierte Trident Installationen. Wenn Sie eine Version von Trident vor 1.3.2 verwendet und ein Upgrade mit vorhandenen Volumes durchführen, müssen Sie diesen Wert einstellen, um auf die alten Volumes zuzugreifen, die über die Volume-Name-Methode zugeordnet wurden.
 a| 
`netappdvp-`

|===
Der `solidfire-san` Treiber unterstützt Docker Swarm nicht.



=== Beispiel für eine Konfigurationsdatei für die Element Software

[listing]
----
{
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": "https://admin:admin@192.168.160.3/json-rpc/8.0",
    "SVIP": "10.0.0.7:3260",
    "TenantName": "docker",
    "InitiatorIFace": "default",
    "Types": [
        {
            "Type": "Bronze",
            "Qos": {
                "minIOPS": 1000,
                "maxIOPS": 2000,
                "burstIOPS": 4000
            }
        },
        {
            "Type": "Silver",
            "Qos": {
                "minIOPS": 4000,
                "maxIOPS": 6000,
                "burstIOPS": 8000
            }
        },
        {
            "Type": "Gold",
            "Qos": {
                "minIOPS": 6000,
                "maxIOPS": 8000,
                "burstIOPS": 10000
            }
        }
    ]
}
----