---
sidebar: sidebar 
permalink: trident-docker/volumes-docker.html 
keywords: create volumes, astra trident, trident for docker, docker, docker volume 
summary: 'Um Volumes zu erstellen, verwenden Sie die Standardbefehle `docker volume` mit dem bei Bedarf angegebenen Astra Trident-Treibernamen.' 
---
= Arbeiten mit Volumes
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Volumes können ganz einfach mit den Standardbefehlen erstellt, geklont und entfernt `docker volume` werden. Der Astra Trident-Treibername wird bei Bedarf angegeben.



== Erstellen eines Volumes

* Erstellen Sie ein Volume mit einem Treiber unter Verwendung des Standardnamens:
+
[listing]
----
docker volume create -d netapp --name firstVolume
----
* Erstellung eines Volumes mit einer bestimmten Astra Trident Instanz:
+
[listing]
----
docker volume create -d ntap_bronze --name bronzeVolume
----
+

NOTE: Wenn Sie keine angebenlink:volume-driver-options.html["Optionen"^], werden die Standardeinstellungen für den Treiber verwendet.

* Überschreiben Sie die Standard-Volume-Größe. Beachten Sie das folgende Beispiel, um ein 20 gib-Volume mit einem Treiber zu erstellen:
+
[listing]
----
docker volume create -d netapp --name my_vol --opt size=20G
----
+

TIP: Die Volume-Größen werden als Strings angegeben, die einen ganzzahligen Wert mit optionalen Einheiten enthalten (Beispiel: 10G, 20GB, 3tib). Wenn keine Einheiten angegeben werden, ist der Standardwert G. Größeneinheiten können entweder als Kräfte von 2 (B, KiB, MiB, gib, tib) oder mit einer Leistung von 10 (B, KB, MB, GB, TB) angegeben werden. Auf Kurzschluss und Einheiten werden 2 Kräfte (G = gib, T = tib, …) verwendet.





== Entfernen Sie ein Volume

* Entfernen Sie das Volume wie jedes andere Docker Volume:
+
[listing]
----
docker volume rm firstVolume
----
+

IMPORTANT: Bei der Verwendung des `solidfire-san` Treibers löscht und löscht das obige Beispiel das Volume.



Führen Sie die nachstehenden Schritte zum Upgrade von Astra Trident für Docker durch.



== Klonen Sie ein Volume

Bei Verwendung der `ontap-nas`, , `ontap-san` `solidfire-san` und `gcp-cvs storage drivers`, kann Astra Trident Volumes klonen. Wenn Sie die oder `ontap-nas-economy`-Treiber verwenden `ontap-nas-flexgroup`, wird das Klonen nicht unterstützt. Wenn Sie ein neues Volume von einem vorhandenen Volume erstellen, wird ein neuer Snapshot erstellt.

* Überprüfen Sie das Volume, um die Snapshots aufzuzählen:
+
[listing]
----
docker volume inspect <volume_name>
----
* Erstellen Sie ein neues Volume von einem vorhandenen Volume aus. Dadurch wird ein neuer Snapshot erstellt:
+
[listing]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume>
----
* Erstellen Sie ein neues Volume anhand eines vorhandenen Snapshots auf einem Volume. Dadurch wird kein neuer Snapshot erstellt:
+
[listing]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume> -o fromSnapshot=<source_snap_name>
----




=== Beispiel

[listing]
----
docker volume inspect firstVolume

[
    {
        "Driver": "ontap-nas",
        "Labels": null,
        "Mountpoint": "/var/lib/docker-volumes/ontap-nas/netappdvp_firstVolume",
        "Name": "firstVolume",
        "Options": {},
        "Scope": "global",
        "Status": {
            "Snapshots": [
                {
                    "Created": "2017-02-10T19:05:00Z",
                    "Name": "hourly.2017-02-10_1505"
                }
            ]
        }
    }
]

docker volume create -d ontap-nas --name clonedVolume -o from=firstVolume
clonedVolume

docker volume rm clonedVolume
docker volume create -d ontap-nas --name volFromSnap -o from=firstVolume -o fromSnapshot=hourly.2017-02-10_1505
volFromSnap

docker volume rm volFromSnap
----


== Zugriff auf extern erstellte Volumes

Sie können über Trident *only* auf extern erstellte Blockgeräte (oder deren Clones) zugreifen, wenn sie keine Partitionen haben und ihr Dateisystem von Astra Trident unterstützt wird (z.B.: Ein `ext4`-formatiertes `/dev/sdc1` wird nicht über Astra Trident zugänglich sein).
