---
sidebar: sidebar 
permalink: trident-rn.html 
keywords: 'what"s new, new features, enhancements, known issues, resolved issues, troubleshooting' 
summary: NetApp verbessert seine Produkte und Services kontinuierlich. Im Folgenden finden Sie einige der neuesten Funktionen, Verbesserungen und Bugfixes in der neuesten Version von Astra Trident. 
---
= Was ist neu
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Versionshinweise liefern Informationen zu den neuen Funktionen, Verbesserungen und Bugfixes in der aktuellen Version von Astra Trident.


WARNING: Die `tridentctl` Binärdatei für Linux, die in der ZIP-Datei des Installers enthalten ist, ist die getestete und unterstützte Version. Beachten Sie, dass die `macos` im Teil der ZIP-Datei bereitgestellte Binärdatei `/extras` nicht getestet oder unterstützt wird.



== Was ist neu in 24.06



=== Vorgestellt Werden

* **WICHTIG**: Der `limitVolumeSize` Parameter beschränkt jetzt die qtree/LUN Größen in den ONTAP Economy Treibern. Verwenden Sie den neuen  `limitVolumePoolSize` Parameter, um die FlexVol-Größen in diesen Treibern zu steuern. (link:https://github.com/NetApp/trident/issues/341["Ausgabe #341"]).
* Zusätzliche Möglichkeit für iSCSI Selbstheilung, SCSI-Scans durch exakte LUN-ID zu initiieren, wenn veraltete Initiatorgruppen verwendet werden (link:https://github.com/NetApp/trident/issues/883["Ausgabe #883"]).
* Zusätzliche Unterstützung für Volume-Klonvorgänge und Größenänderungsvorgänge, die zulässig waren, selbst wenn sich das Backend im unterbrochenen Modus befindet.
* Zusätzliche Möglichkeit für benutzerdefinierte Protokolleinstellungen, damit der Trident Controller an Astra Trident Node-Pods weitergegeben werden kann
* Unterstützung in Astra Trident wurde hinzugefügt, um REST standardmäßig anstelle von ZAPI für ONTAP-Versionen 9.15.1 und höher zu verwenden.
* Zusätzliche Unterstützung für benutzerdefinierte Volume-Namen und Metadaten auf den ONTAP Storage-Back-Ends für neue persistente Volumes.
* Erweitert den `azure-netapp-files` (ANF)-Treiber, um das Snapshot-Verzeichnis standardmäßig automatisch zu aktivieren, wenn die NFS-Mount-Optionen auf NFS-Version 4.x eingestellt sind
* Bottlerocket-Unterstützung für NFS-Volumes hinzugefügt.
* Unterstützung für die technische Vorschau von Google Cloud NetApp Volumes hinzugefügt.




==== Kubernetes

* Unterstützung für Kubernetes 1.30 hinzugefügt.
* Zusätzliche Fähigkeit für Astra Trident DemonSet, Zombie-Mounts und Restverfolgungsdateien beim Start zu reinigen (link:https://github.com/NetApp/trident/issues/883["Ausgabe #883"]).
* PVC-Beschriftung für dynamischen Import von LUKS-Volumes ( ) hinzugefügt `trident.netapp.io/luksEncryption`link:https://github.com/NetApp/trident/issues/849["Ausgabe #849"].
* ANF-Treiber wurde um Topologiebewusstsein erweitert.
* Unterstützung für Windows Server 2022-Knoten hinzugefügt.




=== Korrekturen

* Astra Trident Installationsfehler aufgrund veralteter Transaktionen wurden behoben.
* Tridentctl wurde behoben, um Warnmeldungen von Kubernetes ( ) zu ignorierenlink:https://github.com/NetApp/trident/issues/892["Ausgabe #892"].
* Die Astra Trident Controller-Priorität wurde zu ( ) geändert `SecurityContextConstraint` `0`link:https://github.com/NetApp/trident/issues/887["Ausgabe #887"].
* ONTAP-Treiber akzeptieren jetzt Volumengrößen unter 20MiB (link:https://github.com/NetApp/trident/issues/885["Problem[#885"]).
* Astra Trident wurde korrigiert, um ein Verkleinern von FlexVols während des Größenänderungsvorgangs für den ONTAP-SAN Treiber zu verhindern.
* Fehler beim Import von ANF-Volumes mit NFS v4.1 behoben.




=== Abschreibungen

* Support für EOL Windows Server 2019 wurde entfernt.




== Änderungen in 24.02



=== Vorgestellt Werden

* Unterstützung für Cloud Identity wurde zugefügt.
+
** AKS mit ANF – Azure Workload Identity wird als Cloud-Identität verwendet.
** EKS mit FSxN – AWS IAM-Rolle wird als Cloud-Identität verwendet.


* Unterstützung für die Installation von Astra Trident als Add-on auf EKS Cluster von der EKS-Konsole aus hinzugefügt.
* Zusätzliche Möglichkeit zur Konfiguration und Deaktivierung der iSCSI-Selbstheilung (link:https://github.com/NetApp/trident/issues/864["Ausgabe #864"]).
* ONTAP-Treiber wurden um FSX Personality erweitert, um die Integration mit AWS IAM und SecretsManager zu ermöglichen und Astra Trident zu ermöglichen FSX-Volumes mit Backups zu löschen (link:https://github.com/NetApp/trident/issues/453["Ausgabe #453"]).




==== Kubernetes

* Unterstützung für Kubernetes 1.29 hinzugefügt.




=== Korrekturen

* ACP-Warnmeldungen wurden behoben, wenn ACP nicht aktiviert ist (link:https://github.com/NetApp/trident/issues/866["Ausgabe #866"]).
* Es wurde eine Verzögerung von 10 Sekunden hinzugefügt, bevor eine Klonaufteilung während der Snapshot-Löschung für ONTAP-Treiber durchgeführt wird, wenn ein Klon mit dem Snapshot verknüpft ist.




=== Abschreibungen

* In-toto-Teststationen-Framework aus Multi-Plattform-Image-Manifesten entfernt.




== Änderungen in 23.10



=== Korrekturen

* Die Volume-Erweiterung wurde behoben, wenn eine neue angeforderte Größe kleiner ist als die Gesamtgröße für ONTAP-nas- und ONTAP-nas-FlexGroup-Speichertreiber (link:https://github.com/NetApp/trident/issues/834["Ausgabe #834"^]).
* Die Volume-Größe wurde festgelegt, um nur die nutzbare Größe des Volumes während des Imports für ONTAP-nas- und ONTAP-nas-FlexGroup-Speichertreiber anzuzeigen (link:https://github.com/NetApp/trident/issues/722["Ausgabe #722"^]).
* FlexVol Namenskonvertierung für ONTAP-NAS-Economy wurde korrigiert.
* Das Astra Trident Initialisierungsproblem wurde bei einem Neustart des Nodes auf einem Windows Node behoben.




=== Vorgestellt Werden



==== Kubernetes

Unterstützung für Kubernetes 1.28 hinzugefügt.



==== Astra Trident

* Unterstützung für die Nutzung von Azure Managed Identities (AMI) mit Azure-netapp-Files Storage-Treibern hinzugefügt.
* Zusätzliche Unterstützung für NVMe over TCP für den ONTAP-SAN-Treiber.
* Hinzugefügt Möglichkeit, die Bereitstellung eines Volumes anzuhalten, wenn Backend auf suspendiert Zustand von Benutzer () gesetzt wirdlink:https://github.com/NetApp/trident/issues/558["Ausgabe #558"^].




=== Erweiterte Funktionen in Astra Control verfügbar

Mit Astra Trident 23.10 ist eine neue Software-Komponente namens Astra Control Provisioner für lizenzierte Astra Control Benutzer verfügbar. Mit diesem provisioner erhalten Sie Zugriff auf umfassende Funktionen für erweitertes Management und Storage-Bereitstellung, die Astra Trident selbst unterstützt. Für Version 23.10 sind dies unter anderem folgende Funktionen:

* Backup- und Restore-Funktionen für Applikationen mit ontap-nas-Economy-Storage-Back-Ends mit Treiberunterstützung
* Verbesserte Sicherheit des Storage-Backends mit Kerberos 5-Verschlüsselung
* Datenwiederherstellung mithilfe eines Snapshots
* SnapMirror Verbesserungen


link:https://docs.netapp.com/us-en/astra-control-center/release-notes/whats-new.html["Erfahren Sie mehr über die Astra Control Provisioner."^]



== Änderungen in 23.07.1

*Kubernetes:* Festes Dämonenset-Löschen zur Unterstützung von Upgrades ohne Ausfallzeiten (link:https://github.com/NetApp/trident/issues/740["Ausgabe #740"^]).



== Änderungen in 23.07



=== Korrekturen



==== Kubernetes

* Trident Upgrade wurde behoben, um alte Pods, die im Abschlusszustand stecken, zu ignorieren (link:https://github.com/NetApp/trident/issues/740["Ausgabe #740"^]).
* Tolerierung zur Definition "transient-Trident-Version-pod" () hinzugefügtlink:https://github.com/NetApp/trident/issues/795["Ausgabe #795"^].




==== Astra Trident

* ONTAP-ZAPI-Anforderungen wurden behoben, um sicherzustellen, dass die LUN-Seriennummern abgefragt werden, wenn LUN-Attribute zur Identifizierung und Behebung von Ghost-iSCSI-Geräten während der Knotenstagevorgänge abgerufen werden.
* Fehlerbehandlung im Speichertreibercode () behobenlink:https://github.com/NetApp/trident/issues/816["Ausgabe #816"^].
* Feste Quota-Größe bei Verwendung von ONTAP-Treibern mit use-Rest=true.
* Erstellung von LUN-Klonen in ontap-san-Economy wurde korrigiert.
* Revert publish info field from to `devicePath`; added Logic to populate and Recover (in einigen Fällen) `devicePath` field `rawDevicePath`.




=== Vorgestellt Werden



==== Kubernetes

* Unterstützung für den Import vorbereitgestellter Snapshots wurde hinzugefügt.
* Minimierte Bereitstellung und Dämonset linux-Berechtigungen (link:https://github.com/NetApp/trident/issues/817["Ausgabe #817"^]).




==== Astra Trident

* Es wird kein Statusfeld mehr für „Online“ Volumes und Snapshots gemeldet.
* Aktualisiert den Backend-Zustand, wenn das ONTAP-Backend offline ist (link:https://github.com/NetApp/trident/issues/801["Probleme #801"^], link:https://github.com/NetApp/trident/issues/543["#543"^]).
* Die LUN-Seriennummer wird während des Workflows „ControllerVolumePublish“ immer abgerufen und veröffentlicht.
* Zusätzliche Logik zur Überprüfung der Seriennummer und Größe des iSCSI Multipath-Geräts hinzugefügt.
* Zusätzliche Überprüfung für iSCSI-Volumes, um sicherzustellen, dass das richtige Multipath-Gerät nicht bereitgestellt wird.




==== Experimentelle Verbesserung

Unterstützung für NVMe over TCP für den ONTAP-SAN-Treiber wurde um eine technische Vorschau erweitert.



==== Dokumentation

Viele organisatorische und formatierte Verbesserungen wurden vorgenommen.



=== Abschreibungen



==== Kubernetes

* Unterstützung für v1beta1-Snapshots wurde entfernt.
* Unterstützung für Pre-CSI-Volumes und Speicherklassen wurde entfernt.
* Aktualisiertes, mindestens unterstütztes Kubernetes auf 1.22




== Änderungen in 23.04


IMPORTANT: Volume-Trennung für ONTAP-SAN-*-Volumes erzwingen wird nur bei Kubernetes-Versionen mit aktiviertem Non-Graceful Node Shutdown Feature Gate unterstützt. Die Option zum erzwingen des Abtrennens muss zur Installationszeit mit dem Trident-Installer-Flag aktiviert sein `--enable-force-detach`.



=== Korrekturen

* Trident-Operator zur Verwendung von IPv6-localhost für die Installation festgelegt, wenn in Spec angegeben.
* Trident Operator Cluster Rollenberechtigungen wurden korrigiert, um mit den Paketberechtigungen synchronisiert zu sein (link:https://github.com/NetApp/trident/issues/799["Ausgabe #799"^]).
* Problem beim Anhängen von RAW-Block-Volumes auf mehreren Knoten im RWX-Modus behoben.
* Unterstützung von FlexGroup-Klonen und Volume-Import für SMB-Volumes wurde korrigiert.
* Problem behoben, bei dem der Trident-Controller nicht sofort heruntergefahren werden konnte (link:https://github.com/NetApp/trident/issues/811["Ausgabe #811"]).
* Es wurde ein Fix zur Auflistung aller igroup-Namen hinzugefügt, die mit einer angegebenen LUN verbunden sind, die mit ontap-san-* Treibern bereitgestellt wurde.
* Korrektur hinzugefügt, um die Ausführung externer Prozesse bis zum Abschluss zu ermöglichen.
* Kompilierungsfehler für s390-Architektur () behobenlink:https://github.com/NetApp/trident/issues/537["Ausgabe #537"].
* Falsche Protokollierungsebene bei Volume-Mount-Operationen () behobenlink:https://github.com/NetApp/trident/issues/781["Ausgabe #781"].
* Fehler bei der Assertion des potenziellen Typs () behobenlink:https://github.com/NetApp/trident/issues/802["Ausgabe #802"].




=== Vorgestellt Werden

* Kubernetes:
+
** Unterstützung für Kubernetes 1.27 hinzugefügt.
** Unterstützung für den Import von LUKS-Volumes wurde hinzugefügt.
** Zusätzliche Unterstützung für den ReadWriteOncePod PVC-Zugriffsmodus.
** Unterstützung für Force-Trennen für ONTAP-SAN-*-Volumes während nicht-Graceful Node Shutdown-Szenarien hinzugefügt.
** Alle ONTAP-SAN-* Volumes verwenden nun Initiatorgruppen pro Node. LUNs werden nur Initiatorgruppen zugeordnet, während sie aktiv auf diesen Nodes veröffentlicht werden, um unsere Sicherheit zu verbessern. Bestehende Volumes werden opportunistisch auf das neue igroup Schema umgestellt, wenn Trident feststellt, dass es sicher ist, dies zu tun, ohne aktive Workloads zu beeinträchtigen (link:https://github.com/NetApp/trident/issues/758["Ausgabe #758"]).
** Verbesserte die Trident-Sicherheit durch Bereinigung nicht genutzter Trident-gemanagter Initiatorgruppen aus ONTAP-SAN-* Back-Ends.


* Zusätzliche Unterstützung für SMB Volumes mit Amazon FSX für die ontap-nas-Wirtschaft und ontap-nas-flexgroup-Storage-Treiber.
* Unterstützung von SMB-Freigaben mit ontap-nas, ontap-nas-Economy und ontap-nas-Flexgroup-Storage-Treibern hinzugefügt.
* Unterstützung für arm64 Knoten () hinzugefügtlink:https://github.com/NetApp/trident/issues/732["Ausgabe #732"].
* Verbessertes Trident-Shutdown-Verfahren durch Deaktivierung von API-Servern zuerst (link:https://github.com/NetApp/trident/issues/811["Ausgabe #811"]).
* Cross-Plattform-Build-Unterstützung für Windows- und arm64-Hosts zu Makefile hinzugefügt; siehe BUILD.md.




=== Abschreibungen

**Kubernetes:** bei der Konfiguration von ONTAP-san- und ONTAP-san-Economy-Treibern werden keine über Backend scoped igroups mehr erstellt (link:https://github.com/NetApp/trident/issues/758["Ausgabe #758"]).



== Änderungen in 23.01.1



=== Korrekturen

* Trident-Operator zur Verwendung von IPv6-localhost für die Installation festgelegt, wenn in Spec angegeben.
* Trident Operator Cluster Rollenberechtigungen wurden korrigiert, um mit den Bundle-Berechtigungen synchronisiert zu seinlink:https://github.com/NetApp/trident/issues/799["Ausgabe #799"^].
* Korrektur hinzugefügt, um die Ausführung externer Prozesse bis zum Abschluss zu ermöglichen.
* Problem beim Anhängen von RAW-Block-Volumes auf mehreren Knoten im RWX-Modus behoben.
* Unterstützung von FlexGroup-Klonen und Volume-Import für SMB-Volumes wurde korrigiert.




== Änderungen in 23.01


IMPORTANT: Kubernetes 1.27 wird jetzt in Trident unterstützt. Aktualisieren Sie Astra Trident vor dem Upgrade von Kubernetes.



=== Korrekturen

* Kubernetes: Hinzufügen von Optionen zum Ausschluss der Pod-Sicherheitsrichtlinie zur Korrektur von Trident-Installationen über Helm (link:https://github.com/NetApp/trident/issues/794["Ausgaben #783, #794"^]).




=== Vorgestellt Werden

.Kubernetes
* Zusätzliche Unterstützung für Kubernetes 1.26
* Verbesserte allgemeine Nutzung der Trident RBAC-Ressourcen (link:https://github.com/NetApp/trident/issues/757["Ausgabe #757"^]).
* Verbesserte Automatisierung zum Erkennen und Beheben defekter oder veralteter iSCSI Sitzungen auf Host Nodes
* Unterstützung für Erweiterung der LUKS-verschlüsselten Volumes hinzugefügt.
* Kubernetes: Unterstützung für die Rotation von Anmeldeinformationen für LUKS-verschlüsselte Volumes hinzugefügt.


.Astra Trident
* Zusätzlicher Support für SMB Volumes mit Amazon FSX für ONTAP für den ontap-nas-Storage-Treiber
* Unterstützung für NTFS-Berechtigungen bei der Verwendung von SMB-Volumes hinzugefügt.
* Zusätzlicher Support für Storage Pools für GCP Volumes mit CVS Service Level.
* Unterstützung für optionale Verwendung von flexgroupAggregateList bei der Erstellung von FlexGroups mit dem ontap-nas-flexgroup Storage-Treiber hinzugefügt.
* Verbesserte Performance für den ontap-nas-Economy-Storage-Treiber beim Management mehrerer FlexVols.
* Aktivierte Daten-LIF-Updates für alle ONTAP-NAS-Speichertreiber.
* Aktualisierte die Namenskonvention für Trident Deployment und DemonSet zur Berücksichtigung des Host-Node-Betriebssystems.




=== Abschreibungen

* Kubernetes: Aktualisierte die minimal unterstützte Version von Kubernetes auf 1.21.
* Daten-LIFs sollten beim Konfigurieren von oder `ontap-san-economy` Treibern nicht mehr angegeben werden `ontap-san`.




== Änderungen in 22.10

*Vor dem Upgrade auf Astra Trident 22.10 müssen Sie die folgenden wichtigen Informationen lesen.*

[WARNING]
.<starke>kritische Informationen über Astra Trident 22.10</strong>
====
* Kubernetes 1.25 wird jetzt in Trident unterstützt. Vor dem Upgrade auf Kubernetes 1.25 müssen Sie den Astra Trident auf 22.10 aktualisieren.
* Astra Trident setzt jetzt die Verwendung der Multipathing-Konfiguration in SAN-Umgebungen strikt durch, mit einem empfohlenen Wert von `find_multipaths: no` in der Multipath.conf Datei.
+
Die Verwendung einer nicht-Multipathing-Konfiguration oder die Verwendung von `find_multipaths: yes` oder `find_multipaths: smart` Wert in der Datei Multipath.conf führt zu Mount-Fehlern. Trident empfiehlt die Verwendung von `find_multipaths: no` seit Version 21.07.



====


=== Korrekturen

* Problem spezifisch für ONTAP-Backend erstellt mit `credentials` Feld nicht online kommen während 22.07.0 Upgrade (link:https://github.com/NetApp/trident/issues/759["Ausgabe #759"^]).
* **Docker:** Es wurde ein Problem behoben, dass das Docker Volume Plugin in einigen Umgebungen nicht startenlink:https://github.com/NetApp/trident/issues/760["Ausgabe #760"^] konnte (link:https://github.com/NetApp/trident/issues/548["Ausgabe #548"^] und ).
* Festes SLM-Problem speziell für ONTAP-SAN-Back-Ends, das sicherstellt, dass nur eine Teilmenge von Daten-LIFs, die zu den Berichterstellungs-Nodes gehören, veröffentlicht wird.
* Es wurde ein Performance-Problem behoben, bei dem unnötige Scans für iSCSI-LUNs beim Anschließen eines Volumes aufgetreten sind.
* Granulare Wiederholungen innerhalb des Astra Trident iSCSI-Workflows entfernt, um schnell zu scheitern und externe Wiederholungsintervalle zu reduzieren.
* Das Problem wurde behoben, bei dem beim Spülen eines iSCSI-Geräts ein Fehler zurückgegeben wurde, als das entsprechende Multipath-Gerät bereits gespült wurde.




=== Vorgestellt Werden

* Kubernetes:
+
** Zusätzliche Unterstützung für Kubernetes 1.25 Vor dem Upgrade auf Kubernetes 1.25 müssen Sie den Astra Trident auf 22.10 aktualisieren.
** Hinzufügung eines separaten ServiceAccount, ClusterRole und ClusterBinding für die Trident Deployment und DemonSet, um zukünftige Berechtigungsverbesserungen zu ermöglichen.
** Unterstützung für hinzugefügtlink:https://docs.netapp.com/us-en/trident/trident-use/volume-share.html["Namespace-übergreifende Volume-Freigabe"].


* Alle Trident `ontap-*` Storage-Treiber funktionieren jetzt mit der ONTAP REST API.
* Neuer Operator yaml (`bundle_post_1_25.yaml`) ohne A `PodSecurityPolicy` zur Unterstützung von Kubernetes 1.25 hinzugefügt.
* Für `ontap-san` und `ontap-san-economy` Speichertreiber hinzugefügtlink:https://docs.netapp.com/us-en/trident/trident-reco/security-luks.html["Unterstützung für LUKS-verschlüsselte Volumes"].
* Unterstützung für Windows Server 2019-Knoten hinzugefügt.
* Über den `azure-netapp-files` Speichertreiber hinzugefügtlink:https://docs.netapp.com/us-en/trident/trident-use/anf.html["Unterstützung für SMB Volumes auf Windows Nodes"].
* Die automatische MetroCluster-Umschalterkennung für ONTAP-Treiber ist jetzt allgemein verfügbar.




=== Abschreibungen

* **Kubernetes:** Aktualisiert unterstützt mindestens Kubernetes auf 1.20.
* Astra Data Store (ADS)-Treiber entfernt.
* Unterstützung für und `smart` Optionen für `find_multipaths` das Konfigurieren von Multipathing für Arbeitsknoten für iSCSI wurde entfernt `yes`.




== Änderungen in 22.07



=== Korrekturen

**Kubernetes**

* Problem wurde behoben, um boolesche Werte und Zahlenwerte für die Node-Auswahl bei der Konfiguration von Trident mit Helm oder dem Trident Operator zu behandeln. (link:https://github.com/NetApp/trident/issues/700["GitHub Ausgabe #700"^])
* Problem beim Umgang mit Fehlern aus dem nicht-CHAP-Pfad behoben, sodass kubelet erneut versuchen wird, wenn er fehlschlägt. link:https://github.com/NetApp/trident/issues/736["GitHub Ausgabe #736"^])




=== Vorgestellt Werden

* Übergang von k8s.gcr.io zu Registry.k8s.io als Standard-Registry für CSI-Bilder
* ONTAP-SAN Volumes werden jetzt Initiatorgruppen pro Node verwenden und LUNs nur Initiatorgruppen zuordnen, während diese Nodes aktiv veröffentlicht werden, um unsere Sicherheit zu verbessern. Vorhandene Volumes werden opportunistisch auf das neue igroup-Schema umgestellt, wenn Astra Trident feststellt, dass es sicher ist, dies ohne aktive Workloads zu beeinträchtigen.
* Enthält eine ResourceQuota mit Trident-Installationen, um sicherzustellen, dass Trident DemonSet geplant ist, wenn die PriorityClass-Nutzung standardmäßig beschränkt ist.
* Unterstützung für Netzwerkfunktionen für den Azure NetApp Files-Treiber hinzugefügt. (link:https://github.com/NetApp/trident/issues/717["GitHub Ausgabe #717"^])
* Technische Vorschau Automatische MetroCluster-Umschalterkennung zu ONTAP-Treibern hinzugefügt. (link:https://github.com/NetApp/trident/issues/228["GitHub Ausgabe #228"^])




=== Abschreibungen

* **Kubernetes:** Aktualisiert unterstützt mindestens Kubernetes auf 1.19.
* Back-End-Konfiguration ermöglicht nicht mehr mehrere Authentifizierungstypen in einer einzigen Konfiguration.




=== Umzüge

* Der AWS CVS-Treiber (veraltet seit 22.04) wurde entfernt.
* Kubernetes
+
** Keine unnötige SYS_ADMIN-Funktion von Node-Pods entfernt.
** Verringert die Nodevorbereitung auf einfache Host-Info und aktive Serviceerkennung, um eine Bestätigung für den bestmöglichen Aufwand zu machen, dass NFS/iSCSI-Dienste auf Worker-Knoten verfügbar sind.






=== Dokumentation

Ein neuer link:https://docs.netapp.com/us-en/trident/trident-reference/pod-security.html["Pod-Sicherheitsstandards"]Abschnitt (PSS) mit detaillierten Berechtigungen wurde hinzugefügt, die Astra Trident bei der Installation aktiviert hat.



== Änderungen in 22.04

NetApp verbessert seine Produkte und Services kontinuierlich. Im Folgenden finden Sie einige der neuesten Funktionen von Astra Trident: Frühere Versionen finden Sie unter https://docs.netapp.com/us-en/trident/earlier-versions.html["Frühere Versionen der Dokumentation"].


IMPORTANT: Wenn Sie ein Upgrade von einem früheren Trident-Release durchführen und Azure NetApp Files verwenden, ist der ``location``Parameter config jetzt ein obligatorisches Single-Feld.



=== Korrekturen

* Verbessertes Analysieren von iSCSI-Initiatornamen. (link:https://github.com/NetApp/trident/issues/681["GitHub Ausgabe #681"^])
* Das Problem wurde behoben, bei dem CSI-Speicherklassenparameter nicht zulässig waren. (link:https://github.com/NetApp/trident/issues/598["GitHub Ausgabe #598"^])
* Doppelte Schlüsseldeklaration im Trident CRD behoben. (link:https://github.com/NetApp/trident/issues/671["GitHub Ausgabe #671"^])
* Fehlerhafte CSI-Snapshot-Protokolle wurden korrigiert. (link:https://github.com/NetApp/trident/issues/629["GitHub Ausgabe #629"^]))
* Problem beim Aufheben der Veröffentlichung von Volumes auf gelöschten Nodes behoben. (link:https://github.com/NetApp/trident/issues/691["GitHub Ausgabe #691"^])
* Zusätzliche Bearbeitung von Inkonsistenzen im Dateisystem auf Blockgeräten. (link:https://github.com/NetApp/trident/issues/656["GitHub Ausgabe #656"^])
* Problem beim Abrufen von Auto-Support-Bildern beim Festlegen des Flags während der Installation behoben `imageRegistry`. (link:https://github.com/NetApp/trident/issues/715["GitHub Ausgabe #715"^])
* Es wurde ein Problem behoben, bei dem der Azure NetApp Files-Treiber ein Volume mit mehreren Exportregeln nicht klonen konnte.




=== Vorgestellt Werden

* Eingehende Verbindungen zu den sicheren Endpunkten von Trident erfordern jetzt mindestens TLS 1.3. (link:https://github.com/NetApp/trident/issues/698["GitHub Ausgabe #698"^])
* Trident fügt jetzt HSTS-Header zu den Antworten von seinen sicheren Endpunkten hinzu.
* Trident versucht nun, die Azure NetApp Files unix Berechtigungsfunktion automatisch zu aktivieren.
* *Kubernetes*: Trident Demonset wird jetzt in der Klasse mit System-Node-kritischer Priorität ausgeführt. (link:https://github.com/NetApp/trident/issues/694["GitHub Ausgabe #694"^])




=== Umzüge

E-Series-Treiber (deaktiviert seit 20.07) wurde entfernt.



== Änderungen in 22.01.1



=== Korrekturen

* Problem beim Aufheben der Veröffentlichung von Volumes auf gelöschten Nodes behoben. (link:https://github.com/NetApp/trident/issues/691["GitHub Ausgabe #691"])
* Fester Panik beim Zugriff auf Nil-Felder für den aggregierten Speicherplatz in den ONTAP API Antworten.




== Änderungen in 22.01.0



=== Korrekturen

* *Kubernetes:* Erhöhung der Neuzulassung der Knotenregistrierung für große Cluster.
* Das Problem wurde behoben, bei dem der Azure-netapp-Files Treiber von mehreren Ressourcen mit demselben Namen verwirrt werden konnte.
* ONTAP SAN IPv6 Daten-LIFs funktionieren jetzt, wenn sie mit Klammern angegeben sind.
* Das Problem wurde behoben, bei dem der Import eines bereits importierten Volumes das EOF zurückgibt, sodass PVC in den ausstehenden Zustand zurückbleibt. (link:https://github.com/NetApp/trident/issues/489["GitHub Ausgabe #489"])
* Problem behoben, wenn Astra Trident die Performance verlangsamt, wenn > 32 Snapshots auf einem SolidFire Volume erstellt werden.
* SHA-1 wurde durch SHA-256 bei der Erstellung eines SSL-Zertifikats ersetzt.
* Azure NetApp Files-Treiber wurde behoben, um doppelte Ressourcennamen zu erlauben und Vorgänge auf einen einzelnen Speicherort zu beschränken.
* Azure NetApp Files-Treiber wurde behoben, um doppelte Ressourcennamen zu erlauben und Vorgänge auf einen einzelnen Speicherort zu beschränken.




=== Vorgestellt Werden

* Verbesserungen von Kubernetes:
+
** Zusätzliche Unterstützung für Kubernetes 1.23
** Fügen Sie bei der Installation über Trident Operator oder Helm Planungsoptionen für Trident Pods hinzu. (link:https://github.com/NetApp/trident/issues/651["GitHub Ausgabe #651"^])


* Erlauben Sie regionenübergreifende Volumes im GCP-Treiber. (link:https://github.com/NetApp/trident/issues/633["GitHub Ausgabe #633"^])
* Unterstützung für die Option „unixPermissions“ für Azure NetApp Files Volumes wurde hinzugefügt. (link:https://github.com/NetApp/trident/issues/666["GitHub Ausgabe #666"^])




=== Abschreibungen

Die Trident REST-Schnittstelle kann nur unter 127.0.0.1 oder [: 1] Adressen zuhören und bedient werden



== Änderungen in 21.10.1


WARNING: In der Version v21.10.0 kann der Trident Controller in den CrashLoopBackOff-Status versetzt werden, wenn ein Node entfernt und dann wieder zum Kubernetes Cluster hinzugefügt wird. Dieses Problem wurde in der Version 21,10,1 behoben (GitHub Ausgabe 669).



=== Korrekturen

* Beim Import eines Volumes auf ein GCP CVS Backend wurde eine potenzielle Race-Bedingung behoben, die zu einem Import führt.
* Es wurde ein Problem behoben, durch das der Trident Controller in den CrashLoopBackOff-Status versetzt werden kann, wenn ein Node entfernt und dann wieder zum Kubernetes Cluster hinzugefügt wird (GitHub Ausgabe 669).
* Das Problem wurde behoben, bei dem SVMs nicht mehr erkannt wurden, wenn kein SVM-Name angegeben wurde (GitHub Problem 612).




== Änderungen in 21.10.0



=== Korrekturen

* Es wurde ein Problem behoben, bei dem Klone von XFS-Volumes nicht auf demselben Node wie das Quell-Volume gemountet werden konnten (GitHub Ausgabe 514).
* Das Problem wurde behoben, bei dem Astra Trident einen fatalen Fehler beim Herunterfahren protokolliert hat (GitHub Ausgabe 597).
* Kubernetes-bezogene Fixes:
+
** Geben Sie den belegten Speicherplatz eines Volumes als Mindestgröße für die Wiederherstellung zurück, wenn Sie Snapshots mit und `ontap-nas-flexgroup` Treibern erstellen `ontap-nas` (GitHub Ausgabe 645).
** Problem behoben, bei dem `Failed to expand filesystem` der Fehler nach der Volume-Größe protokolliert wurde (GitHub Problem 560).
** Problem behoben, bei dem ein Pod in den Status stecken bleiben konnte `Terminating` (GitHub Ausgabe 572).
** Es wurde der Fall behoben, dass ein `ontap-san-economy` FlexVol voller Snapshot-LUNs sein konnte (GitHub Ausgabe 533).
** Problem mit dem benutzerdefinierten YAML-Installationsprogramm mit einem anderen Bild wurde behoben (GitHub Ausgabe 613).
** Berechnung der Snapshot-Größe wurde korrigiert (GitHub Ausgabe 611).
** Das Problem wurde behoben, bei dem alle Astra Trident Installationsprogramme schlicht Kubernetes als OpenShift identifizieren konnten (GitHub Ausgabe 639).
** Der Trident-Operator hat den Abgleich behoben, wenn der Kubernetes-API-Server nicht erreichbar ist (GitHub Ausgabe 599).






=== Vorgestellt Werden

* Unterstützung für GCP-CVS Performance Volumes wurde zugefügt `unixPermissions`.
* Zusätzliche Unterstützung für für für Skalierung optimierte CVS Volumes in GCP im Bereich von 600 gib bis 1 tib.
* Verbesserungen im Zusammenhang mit Kubernetes:
+
** Zusätzliche Unterstützung für Kubernetes 1.22
** Trident Operator und Helm Chart wurde für die Verwendung mit Kubernetes 1.22 aktiviert (GitHub Ausgabe 628).
** Befehl 'Operator image' zu images hinzugefügt `tridentctl` (GitHub Ausgabe 570).






=== Experimentelle Verbesserungen

* Unterstützung für Volume-Replikation im Treiber hinzugefügt `ontap-san`.
* *Tech Preview* REST-Unterstützung für die, `ontap-san` und `ontap-nas-economy` Treiber hinzugefügt `ontap-nas-flexgroup`.




== Bekannte Probleme

Bekannte Probleme erkennen Probleme, die eine erfolgreiche Verwendung des Produkts verhindern könnten.

* Wenn Sie ein Kubernetes-Cluster von 1.24 auf 1.25 oder höher aktualisieren, auf dem Astra Trident installiert ist, müssen Sie values.yaml aktualisieren, damit Sie den `helm upgrade` Befehl auf `true` festlegen `excludePodSecurityPolicy` oder hinzufügen `--set excludePodSecurityPolicy=true` können, bevor Sie das Cluster aktualisieren können.
* Astra Trident erzwingt jetzt ein Leerzeichen `fsType` (`fsType=""`) für Volumes, die nicht die in ihrer StorageClass angegebene haben `fsType`. Bei der Arbeit mit Kubernetes 1.17 oder höher unterstützt Trident die Bereitstellung eines Leereinschübe `fsType` für NFS-Volumes. Für iSCSI-Volumes müssen Sie die auf Ihrer StorageClass festlegen, wenn Sie `fsType` einen mit einem Sicherheitskontext erzwingen `fsGroup`.
* Wenn Sie ein Back-End über mehrere Astra Trident Instanzen hinweg verwenden, sollte jede Back-End-Konfigurationsdatei einen anderen Wert für ONTAP Back-Ends haben `storagePrefix` oder einen anderen für SolidFire Back-Ends verwenden `TenantName`. Astra Trident kann Volumes nicht erkennen, die andere Instanzen von Astra Trident erstellt haben. Es ist erfolgreich, ein vorhandenes Volume auf ONTAP- oder SolidFire-Back-Ends zu erstellen, da Astra Trident die Volume-Erstellung als einen idempotenten Vorgang behandelt. Wenn `storagePrefix` sich die Volumes unterscheiden oder `TenantName` nicht, kann es zu Namenskollisionen für Volumes kommen, die auf demselben Backend erstellt wurden.
* Bei der Installation von Astra Trident (mit `tridentctl` oder dem Trident Operator) und der Verwendung `tridentctl` zur Verwaltung von Astra Trident sollten Sie sicherstellen, dass die `KUBECONFIG` Umgebungsvariable eingestellt ist. Dies ist notwendig, um den Kubernetes-Cluster anzugeben, der `tridentctl` gegen den eingesetzt werden soll. Wenn Sie mit mehreren Kubernetes-Umgebungen arbeiten, sollten Sie sicherstellen, dass die `KUBECONFIG` Datei korrekt bezogen wird.
* Um Online-Speicherplatzrückgewinnung für iSCSI PVS durchzuführen, muss das zugrunde liegende Betriebssystem auf dem Worker-Node möglicherweise Mount-Optionen an das Volume übergeben werden. Dies gilt für RHEL/RedHat CoreOS Instanzen, die das; verlangen `discard` https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["Mount-Option"^], dass die discard mountOption in Ihrem^] enthalten ist[`StorageClass`, um Online-Blockverwerfen zu unterstützen.
* Wenn für den Kubernetes Cluster mehr als eine Instanz von Astra Trident zur Verfügung steht, kann Astra Trident nicht mit anderen Instanzen kommunizieren und kann nicht andere Volumes ermitteln, die sie erstellt haben. Dies führt zu einem unerwarteten und falschen Verhalten, wenn mehrere Instanzen innerhalb eines Clusters ausgeführt werden. Astra Trident sollte nur eine Instanz pro Kubernetes Cluster geben.
* Wenn Astra Trident-basierte `StorageClass` Objekte aus Kubernetes gelöscht werden, während Astra Trident offline ist, entfernt Astra Trident beim wieder-Online-Status die entsprechenden Storage-Klassen nicht aus seiner Datenbank. Sie sollten diese Speicherklassen mit oder der REST-API löschen `tridentctl`.
* Wenn ein Benutzer ein von Astra Trident bereitgestelltes PV löscht, bevor das entsprechende PVC gelöscht wird, löscht Astra Trident nicht automatisch das Back-Volume. Sie sollten das Volume über die REST-API entfernen `tridentctl`.
* ONTAP kann nicht gleichzeitig mehr als ein FlexGroup gleichzeitig bereitstellen, es sei denn, der Satz der Aggregate ist auf jede Bereitstellungsanforderung beschränkt.
* Wenn Sie Astra Trident über IPv6 verwenden, sollten Sie und `dataLIF` in der Backend-Definition in eckigen Klammern angeben `managementLIF`. ``[fd20:8b1e:b258:2000:f816:3eff:feec:0]``Beispiel: .
+

NOTE: Sie können die Angabe auf einem ONTAP-SAN-Backend nicht `dataLIF` machen. Astra Trident erkennt alle verfügbaren iSCSI LIFs und erstellt mit ihnen die Multipath-Sitzung.

* Wenn Sie den `solidfire-san` Treiber mit OpenShift 4.5 verwenden, stellen Sie sicher, dass die zugrunde liegenden Arbeitsknoten MD5 als CHAP-Authentifizierungsalgorithmus verwenden. Sichere, FIPS-konforme CHAP-Algorithmen SHA1, SHA-256 und SHA3-256 sind mit Element 12.7 erhältlich.




== Weitere Informationen

* https://github.com/NetApp/trident["Astra Trident GitHub"^]
* https://netapp.io/persistent-storage-provisioner-for-kubernetes/["Astra Trident Blogs"^]

