---
sidebar: sidebar 
permalink: trident-managing-k8s/uninstall-trident.html 
keywords: uninstall, astra trident, methods, operator, tridentctl, helm, downgrade, obliviate, crds, wipeout, downgrade 
summary: Sie sollten die gleiche Methode verwenden, um Astra Trident zu deinstallieren, die Sie zur Installation von Astra Trident verwendet haben. Wenn Sie eine Fehlerbehebung für Fehler benötigen, die nach einem Upgrade, Abhängigkeitsproblemen oder einem nicht erfolgreichen oder unvollständigen Upgrade beobachtet wurden, sollten Sie Astra Trident deinstallieren und die frühere Version mithilfe der entsprechenden Anweisungen für diese Version neu installieren. 
---
= Deinstallieren Sie Astra Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten die gleiche Methode verwenden, um Astra Trident zu deinstallieren, die Sie zur Installation von Astra Trident verwendet haben.

.Über diese Aufgabe
* Wenn Sie nach einem Upgrade, Abhängigkeitsproblemen oder einem nicht erfolgreichen oder unvollständigen Upgrade eine Korrektur für Fehler benötigen, sollten Sie Astra Trident deinstallieren und die frühere Version mithilfe der entsprechenden Anweisungen neu installierenlink:../earlier-versions.html["Version"]. Dies ist die einzige empfohlene Möglichkeit, _Downgrade_ auf eine frühere Version zu übertragen.
* Für eine einfache Aktualisierung und Neuinstallation entfernt das Deinstallieren von Astra Trident nicht die CRDs oder damit verbundene Objekte, die von Astra Trident erstellt wurden. Wenn Sie Astra Trident und alle seine Daten vollständig entfernen müssen, lesen Sie link:../troubleshooting.html#completely-remove-astra-trident-and-crds["Entfernen Sie Astra Trident und CRDs vollständig"].


.Bevor Sie beginnen
Falls Sie Kubernetes-Cluster stilllegen, müssen Sie alle Applikationen löschen, die Volumes verwenden, die von Astra Trident erstellt wurden, bevor Sie sie deinstallieren. Dadurch wird sichergestellt, dass PVCs auf Kubernetes-Nodes nicht veröffentlicht werden, bevor sie gelöscht werden.



== Bestimmen Sie die ursprüngliche Installationsmethode

Sie sollten die gleiche Methode verwenden, um Astra Trident zu deinstallieren, die Sie verwendet haben, um es zu installieren. Überprüfen Sie vor der Deinstallation, mit welcher Version Sie Astra Trident ursprünglich installiert haben.

. Verwenden Sie, `kubectl get pods -n trident` um die Pods zu untersuchen.
+
** Wenn es keinen Operator POD gibt, wurde Astra Trident mit installiert `tridentctl`.
** Wenn es einen Operator Pod gibt, wurde Astra Trident entweder manuell oder über Helm mit dem Trident Operator installiert.


. Falls es einen Pod gibt, mit können Sie `kubectl describe tproc trident` feststellen, ob Astra Trident mit Helm installiert wurde.
+
** Wenn es ein Helm-Label gibt, wurde Astra Trident mit Helm installiert.
** Wenn es kein Helm-Label gibt, wurde Astra Trident manuell über den Trident Operator installiert.






== Deinstallieren Sie die Installation eines Trident-Operators

Sie können die Installation eines Dreizack-Bedieners manuell oder mithilfe von Helm deinstallieren.



=== Deinstallieren Sie die manuelle Installation

Falls Sie Astra Trident mit dem Operator installiert haben, können Sie es deinstallieren, indem Sie einen der folgenden Schritte ausführen:

. **CR bearbeiten `TridentOrchestrator` und das Deinstallationsflag einstellen**:
+
[listing]
----
kubectl patch torc <trident-orchestrator-name> --type=merge -p '{"spec":{"uninstall":true}}'
----
+
Wenn das `uninstall` Flag auf gesetzt ist `true`, deinstalliert der Trident-Operator Trident, entfernt aber nicht den TridentOrchestrator selbst. Sie sollten den TridentOrchestrator aufräumen und einen neuen erstellen, wenn Sie Trident erneut installieren möchten.

. **Löschen `TridentOrchestrator`**: Durch Entfernen des `TridentOrchestrator` CR, der zur Bereitstellung von Astra Trident verwendet wurde, weisen Sie den Bediener an, Trident zu deinstallieren. Der Operator verarbeitet die Entfernung von `TridentOrchestrator` Astra Trident Deployment und demonset und löscht die Trident-Pods, die er im Rahmen der Installation erstellt hatte.
+
[listing]
----
kubectl delete -f deploy/<bundle.yaml> -n <namespace>
----




=== Deinstallieren Sie Helm-Installation

Wenn Sie Astra Trident mit Helm installiert haben, können Sie es mit deinstallieren `helm uninstall`.

[listing]
----
#List the Helm release corresponding to the Astra Trident install.
helm ls -n trident
NAME          NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
trident       trident         1               2021-04-20 00:26:42.417764794 +0000 UTC deployed        trident-operator-21.07.1        21.07.1

#Uninstall Helm release to remove Trident
helm uninstall trident -n trident
release "trident" uninstalled
----


== Deinstallieren Sie eine `tridentctl` Installation

Verwenden Sie den `uninstall` Befehl in `tridentctl`, um alle mit Astra Trident verbundenen Ressourcen mit Ausnahme der CRDs und zugehörigen Objekte zu entfernen:

[listing]
----
./tridentctl uninstall -n <namespace>
----