---
sidebar: sidebar 
permalink: trident-managing-k8s/upgrade-operator.html 
keywords: upgrade, trident, methods, operator, tridentctl, helm 
summary: Sie können eine bestehende Astra Trident-Installation ganz einfach mithilfe des Bedieners aufrüsten. 
---
= Upgrade einer Astra Trident Installation mit dem Trident Operator oder Helm
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Upgrade von Astra Trident mit dem Trident Operator entweder manuell oder mit Helm durchführen. Sie können von einer Trident-Bedienerinstallation auf eine andere Trident-Bedienerinstallation aktualisieren oder von einer Installation auf eine Trident-Bedienerversion aktualisieren `tridentctl`. Vor dem Upgrade einer Trident-Bedienerinstallation überprüfenlink:upgrade-trident.html#select-an-upgrade-method["Wählen Sie eine Aktualisierungsmethode aus"].



== Aktualisieren einer manuellen Installation

Sie können von einer Installation eines Trident Operators mit Cluster-Umfang auf eine andere Installation eines Trident Operators mit Cluster-Umfang aktualisieren. Alle Astra Trident Versionen 21.01 und höher verwenden einen Operator mit Cluster-Umfang.


NOTE: Um ein Upgrade von Astra Trident durchzuführen, das mit dem Namespace-Scoped-Operator (Versionen 20.07 bis 20.10) installiert wurde, verwenden Sie die Upgrade-Anweisungen für link:../earlier-versions.html["Ihre installierte Version"]Astra Trident.

.Über diese Aufgabe
Trident bietet eine Bundle-Datei, mit der Sie den Operator installieren und zugehörige Objekte für Ihre Kubernetes-Version erstellen können.

* Verwenden Sie für Cluster mit Kubernetes 1.24 link:https://github.com/NetApp/trident/tree/stable/v24.06/deploy/bundle_pre_1_25.yaml["Bundle_pre_1_25.yaml"^].
* Verwenden Sie für Cluster mit Kubernetes 1.25 oder höher link:https://github.com/NetApp/trident/tree/stable/v24.06/deploy/bundle_post_1_25.yaml["Bundle_Post_1_25.yaml"^].


.Bevor Sie beginnen
Stellen Sie sicher, dass Sie ein Kubernetes Cluster verwendenlink:../trident-get-started/requirements.html["Eine unterstützte Kubernetes Version"], das ausgeführt wird.

.Schritte
. Überprüfen Sie die Astra Trident Version:
+
[listing]
----
./tridentctl -n trident version
----
. Löschen Sie den Trident-Operator, der zur Installation der aktuellen Astra Trident-Instanz verwendet wurde. Wenn Sie beispielsweise ein Upgrade von 23.07 durchführen, führen Sie den folgenden Befehl aus:
+
[listing]
----
kubectl delete -f 23.07.0/trident-installer/deploy/<bundle.yaml> -n trident
----
. Wenn Sie Ihre Erstinstallation mithilfe von Attributen angepasst haben `TridentOrchestrator`, können Sie das Objekt bearbeiten `TridentOrchestrator`, um die Installationsparameter zu ändern. Dies kann auch Änderungen umfassen, die an der Angabe gespiegelter Trident- und CSI-Image-Register für den Offline-Modus vorgenommen wurden, Debug-Protokolle aktivieren oder Geheimnisse für die Bildausziehung angeben.
. Installieren Sie Astra Trident mit der richtigen YAML-Bundle-Datei für Ihre Umgebung, wobei _<bundle.yaml>_ auf Ihrer Kubernetes-Version basiert oder ist
`bundle_pre_1_25.yaml` `bundle_post_1_25.yaml` . Wenn Sie beispielsweise Astra Trident 24.06 installieren, führen Sie den folgenden Befehl aus:
+
[listing]
----
kubectl create -f 24.06.0/trident-installer/deploy/<bundle.yaml> -n trident
----




== Aktualisieren einer Helm-Installation

Sie können ein Upgrade für eine Astra Trident Helm Installation durchführen.


WARNING: Wenn Sie ein Kubernetes-Cluster von 1.24 auf 1.25 oder höher aktualisieren, auf dem Astra Trident installiert ist, müssen Sie values.yaml aktualisieren, damit Sie den `helm upgrade` Befehl auf `true` festlegen `excludePodSecurityPolicy` oder hinzufügen `--set excludePodSecurityPolicy=true` können, bevor Sie das Cluster aktualisieren können.

.Schritte
. Wenn Sie link:../trident-get-started/kubernetes-deploy-helm.html#deploy-the-trident-operator-and-install-astra-trident-using-helm["Astra Trident mit Helm installiert"], können Sie verwenden `helm upgrade trident netapp-trident/trident-operator --version 100.2406.0` , um ein Upgrade in einem Schritt. Wenn Sie den Helm Repo nicht hinzugefügt haben oder ihn nicht zum Upgrade verwenden können:
+
.. Laden Sie die neueste Version von Astra Trident von link:https://github.com/NetApp/trident/releases/latest["Die Sektion _Assets_ auf GitHub"^]herunter.
.. Verwenden Sie den `helm upgrade` Befehl where zeigt die Version an `trident-operator-24.06.0.tgz` , auf die Sie aktualisieren möchten.
+
[listing]
----
helm upgrade <name> trident-operator-24.06.0.tgz
----
+

NOTE: Wenn Sie während der Erstinstallation benutzerdefinierte Optionen festlegen (z. B. private, gespiegelte Registrierungen für Trident- und CSI-Images angeben), fügen Sie den Befehl mit `--set` an `helm upgrade`, um sicherzustellen, dass diese Optionen im Aktualisierungsbefehl enthalten sind, andernfalls werden die Werte auf die Standardeinstellung zurückgesetzt.



. Führen Sie aus `helm list`, um zu überprüfen, ob die Karte und die App-Version aktualisiert wurden. Ausführen `tridentctl logs`, um alle Debug-Meldungen zu überprüfen.




== Upgrade von einer `tridentctl` Installation auf einen Trident-Operator

Sie können von einer Installation aus auf die neueste Version des Trident-Bedieners aktualisieren `tridentctl`. Die vorhandenen Back-Ends und VES stehen automatisch zur Verfügung.


NOTE: Bevor Sie zwischen den Installationsmethoden wechseln, lesen Sie link:../trident-get-started/kubernetes-deploy.html#moving-between-installation-methods["Wechseln zwischen den Installationsmethoden"].

.Schritte
. Laden Sie die neueste Version von Astra Trident herunter.
+
[listing]
----
# Download the release required [24.060.0]
mkdir 24.06.0
cd 24.06.0
wget https://github.com/NetApp/trident/releases/download/v24.06.0/trident-installer-24.06.0.tar.gz
tar -xf trident-installer-24.06.0.tar.gz
cd trident-installer
----
. Erstellen Sie die `tridentorchestrator` CRD aus dem Manifest.
+
[listing]
----
kubectl create -f deploy/crds/trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
----
. Stellen Sie den Clusteroperator im selben Namespace bereit.
+
[listing]
----
kubectl create -f deploy/<bundle-name.yaml>

serviceaccount/trident-operator created
clusterrole.rbac.authorization.k8s.io/trident-operator created
clusterrolebinding.rbac.authorization.k8s.io/trident-operator created
deployment.apps/trident-operator created
podsecuritypolicy.policy/tridentoperatorpods created

#Examine the pods in the Trident namespace
NAME                                  READY   STATUS    RESTARTS   AGE
trident-controller-79df798bdc-m79dc   6/6     Running   0          150d
trident-node-linux-xrst8              2/2     Running   0          150d
trident-operator-5574dbbc68-nthjv     1/1     Running   0          1m30s
----
. Erstellen Sie ein `TridentOrchestrator` CR für die Installation von Astra Trident.
+
[listing]
----
cat deploy/crds/tridentorchestrator_cr.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident

kubectl create -f deploy/crds/tridentorchestrator_cr.yaml

#Examine the pods in the Trident namespace
NAME                                READY   STATUS    RESTARTS   AGE
trident-csi-79df798bdc-m79dc        6/6     Running   0          1m
trident-csi-xrst8                   2/2     Running   0          1m
trident-operator-5574dbbc68-nthjv   1/1     Running   0          5m41s
----
. Bestätigen Sie, dass das Upgrade von Trident auf die beabsichtigte Version durchgeführt wurde.
+
[listing]
----
kubectl describe torc trident | grep Message -A 3

Message:                Trident installed
Namespace:              trident
Status:                 Installed
Version:                v24.06.0
----

