---
sidebar: sidebar 
permalink: trident-managing-k8s/upgrade-trident.html 
keywords: upgrade, trident, methods, operator, tridentctl, helm 
summary: Astra Trident folgt einem viermonatigen Release-Intervall und liefert drei wichtige Releases pro Kalenderjahr. Jede neue Version baut auf den vorherigen Versionen auf und bietet neue Funktionen, Performance-Verbesserungen sowie Bug Fixes und Verbesserungen. Führen Sie ein Upgrade mindestens einmal pro Jahr durch, um von den neuen Funktionen in Astra Trident zu profitieren. 
---
= Upgrade Astra Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ab Version 24.02 folgt Astra Trident einem viermonatigen Release-Intervall und liefert drei wichtige Releases pro Kalenderjahr. Jede neue Version baut auf den vorherigen Versionen auf und bietet neue Funktionen, Performance-Verbesserungen, Bug Fixes und Verbesserungen. Wir empfehlen Ihnen, ein Upgrade mindestens einmal pro Jahr durchzuführen, um von den neuen Funktionen in Astra Trident zu profitieren.



== Überlegungen vor dem Upgrade

Bei einem Upgrade auf die neueste Version von Astra Trident sollten Sie Folgendes berücksichtigen:

* In allen Namespaces in einem Kubernetes-Cluster sollte nur eine Astra Trident Instanz installiert werden.
* Astra Trident 23.07 und höher benötigt v1-Volume-Snapshots und unterstützt keine Alpha- oder Beta-Snapshots mehr.
* Wenn Sie Cloud Volumes Service für Google Cloud im erstellt link:../trident-use/gcp.html#learn-about-astra-trident-support-for-cloud-volumes-service-for-google-cloud["CVS-Diensttyp"]haben, müssen Sie die Backend-Konfiguration aktualisieren, um beim Upgrade von Astra Trident 23.01 den Service-Level oder `zoneredundantstandardsw` zu verwenden `standardsw`. Wenn das im Backend nicht aktualisiert `serviceLevel` wird, kann es zu einem Fehlschlagen der Volumes kommen. Weitere Informationen finden Sie unter link:../trident-use/gcp.html#cvs-service-type-examples["Beispiele für CVS-Diensttypen"] .
* Es ist wichtig, dass Sie beim `StorageClasses` Upgrade von Astra Trident verwendet angeben `parameter.fsType`. Sie können löschen und neu erstellen `StorageClasses`, ohne bereits vorhandene Volumes zu unterbrechen.
+
** Dies ist eine **Anforderung** für die Durchsetzung von https://kubernetes.io/docs/tasks/configure-pod-container/security-context/["Sicherheitskontexte"^] SAN-Volumes.
** Das Verzeichnis https://github.com/NetApp/Trident/Tree/Master/Trident-Installer/sample-input[sample input^] enthält Beispiele wie https://github.com/NetApp/Trident/Blob/Master/Trident-Installer/sample-input/Storage-class-Samples/Storage-class-BASIC.yaml.templ[`storage-class-basic.yaml.templ` ^] und Link:https://github.com/NetApp/Trident/BLOB/Master/Trident-Installer/sample-input/Storage-class-Samples/default-Storage-class-aml-^.Bronze[`storage-class-bronze-default.yaml`].
** Weitere Informationen finden Sie unter link:../trident-rn.html["Bekannte Probleme"].






== Schritt 1: Wählen Sie eine Version

Astra Trident-Versionen folgen einer datumbasierten Namenskonvention `YY.MM`, wobei „YY“ die letzten beiden Ziffern des Jahres und „MM“ den Monat darstellt. Dot-Releases folgen einer `YY.MM.X` Konvention, wobei „X“ der Patch-Level ist. Sie wählen die Version, auf die Sie aktualisieren möchten, basierend auf der Version aus, von der Sie aktualisieren.

* Sie können ein direktes Upgrade auf jede Zielversion durchführen, die sich innerhalb eines Fensters mit vier Versionen Ihrer installierten Version befindet. Sie können beispielsweise direkt von 23.04 (oder einem beliebigen 23.04-Punkt-Release) auf 24.06 aktualisieren.
* Wenn Sie ein Upgrade von einer Version außerhalb des Fensters mit vier Releases durchführen, führen Sie ein Upgrade in mehreren Schritten durch. Verwenden Sie die Upgrade-Anweisungen für das, von dem link:../earlier-versions.html["Frühere Version"] Sie aktualisieren, um auf die neueste Version zu aktualisieren, die für das Fenster mit vier Versionen passt. Wenn Sie beispielsweise 22.01 verwenden und ein Upgrade auf 24.06 durchführen möchten:
+
.. Erstes Upgrade von 22.07 auf 23.04.
.. Dann Upgrade von 23.04 auf 24.06.





NOTE: Wenn Sie ein Upgrade über den Trident-Operator auf der OpenShift Container Platform durchführen, sollten Sie auf Trident 21.01.1 oder höher aktualisieren. Der mit 21.01.0 veröffentlichte Trident-Operator enthält ein bekanntes Problem, das in 21.01.1 behoben wurde. Weitere Informationen finden Sie im https://github.com/NetApp/trident/issues/517["Details zur Ausgabe auf GitHub"^].



== Schritt 2: Bestimmen Sie die ursprüngliche Installationsmethode

So ermitteln Sie, welche Version Sie ursprünglich für Astra Trident verwendet haben:

. Verwenden Sie, `kubectl get pods -n trident` um die Pods zu untersuchen.
+
** Wenn es keinen Operator POD gibt, wurde Astra Trident mit installiert `tridentctl`.
** Wenn es einen Operator Pod gibt, wurde Astra Trident entweder manuell oder über Helm mit dem Trident Operator installiert.


. Falls es einen Pod gibt, mit können Sie `kubectl describe torc` feststellen, ob Astra Trident mit Helm installiert wurde.
+
** Wenn es ein Helm-Label gibt, wurde Astra Trident mit Helm installiert.
** Wenn es kein Helm-Label gibt, wurde Astra Trident manuell über den Trident Operator installiert.






== Schritt 3: Wählen Sie eine Upgrade-Methode

Im Allgemeinen sollten Sie mit der gleichen Methode aktualisieren, die Sie für die Erstinstallation verwendet haben, jedoch können Sie link:../trident-get-started/kubernetes-deploy.html#moving-between-installation-methods["Wechseln Sie zwischen den Installationsmethoden"]. Astra Trident bietet zwei Optionen für ein Upgrade.

* link:upgrade-operator.html["Upgrade über den Trident-Operator"]
+

TIP: Wir empfehlen Ihnen, die Überprüfung link:upgrade-operator-overview.html["Den Upgrade-Workflow für Bediener verstehen"]durchzuführen, bevor Sie mit dem Betreiber ein Upgrade durchführen.

* 

