---
sidebar: sidebar 
permalink: trident-use/ontap-san.html 
keywords: trident backend, ontap san, ontap-san, ontap-san-economy, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: Erfahren Sie mehr über die Konfiguration eines ONTAP-Backend mit ONTAP-SAN-Treibern. 
---
= Übersicht über ONTAP SAN-Treiber
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Erfahren Sie mehr über die Konfiguration eines ONTAP-Backend mit ONTAP- und Cloud Volumes ONTAP-SAN-Treibern.



== Details zum ONTAP-SAN-Treiber

Astra Trident bietet die folgenden SAN-Storage-Treiber für die Kommunikation mit dem ONTAP Cluster. Unterstützte Zugriffsmodi sind: _ReadWriteOnce_ (RWO), _ReadOnly Many_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).


IMPORTANT: Wenn Sie Astra Control für Schutz, Recovery und Mobilität verwenden, lesen Sie <<Treiberkompatibilität bei Astra Control>>.

[cols="2, 1, 1, 2, 2"]
|===
| Treiber | Protokoll | VolumeModus | Unterstützte Zugriffsmodi | Unterstützte Filesysteme 


| `ontap-san`  a| 
ISCSI
 a| 
Block-Storage
 a| 
RWO, ROX, RWX, RWOP
 a| 
Kein Filesystem, rohes Block-Gerät



| `ontap-san`  a| 
ISCSI
 a| 
Dateisystem
 a| 
RWO, RWOP

ROX und RWX sind im Filesystem-Volume-Modus nicht verfügbar.
 a| 
`xfs` `ext3`, , `ext4`



| `ontap-san`  a| 
NVMe/TCP

Siehe <<Weitere Überlegungen zu NVMe/TCP>>.
 a| 
Block-Storage
 a| 
RWO, ROX, RWX, RWOP
 a| 
Kein Filesystem, rohes Block-Gerät



| `ontap-san`  a| 
NVMe/TCP

Siehe <<Weitere Überlegungen zu NVMe/TCP>>.
 a| 
Dateisystem
 a| 
RWO, RWOP

ROX und RWX sind im Filesystem-Volume-Modus nicht verfügbar.
 a| 
`xfs` `ext3`, , `ext4`



| `ontap-san-economy`  a| 
ISCSI
 a| 
Block-Storage
 a| 
RWO, ROX, RWX, RWOP
 a| 
Kein Filesystem, rohes Block-Gerät



| `ontap-san-economy`  a| 
ISCSI
 a| 
Dateisystem
 a| 
RWO, RWOP

ROX und RWX sind im Filesystem-Volume-Modus nicht verfügbar.
 a| 
`xfs` `ext3`, , `ext4`

|===


=== Treiberkompatibilität bei Astra Control

Astra Control bietet nahtlosen Schutz, Disaster Recovery und Mobilität (Verschieben von Volumes zwischen Kubernetes-Clustern) für Volumes, die mit den Treibern , `ontap-nas-flexgroup` und `ontap-san` erstellt `ontap-nas` wurden. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/astra-control-center/use/replicate_snapmirror.html#replication-prerequisites["Voraussetzungen für die Astra Control Replikation"^] .

[WARNING]
====
* Verwenden Sie `ontap-san-economy` diese Option nur, wenn die Anzahl der persistenten Volumes voraussichtlich höher ist als link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["Unterstützte ONTAP-Volume-Größen"^].
* Verwenden Sie `ontap-nas-economy` diese Option nur, wenn die Anzahl der persistenten Volumes voraussichtlich höher ist als link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["Unterstützte ONTAP-Volume-Größen"^] und der `ontap-san-economy` Treiber nicht verwendet werden kann.
* Verwenden Sie diese Option nicht `ontap-nas-economy`, wenn Sie voraussehen, dass Datensicherung, Disaster Recovery oder Mobilität erforderlich sind.


====


== Benutzerberechtigungen

Astra geht davon aus, dass Astra Trident entweder als ONTAP- oder SVM-Administrator ausgeführt wird, wobei dieser normalerweise den Cluster-Benutzer, einen SVM-Benutzer oder einen `vsadmin` Benutzer mit einem anderen Namen und derselben Rolle verwendet `admin`. Bei Implementierungen von Amazon FSX for NetApp ONTAP rechnet Astra Trident damit, als ONTAP- oder SVM-Administrator ausgeführt zu werden. Dabei verwendet er den Cluster- `fsxadmin`Benutzer oder einen `vsadmin` SVM-Benutzer oder einen Benutzer mit einem anderen Namen mit derselben Rolle. Der `fsxadmin` Benutzer ist ein eingeschränkter Ersatz für den Cluster-Admin-Benutzer.


NOTE: Wenn Sie den Parameter verwenden `limitAggregateUsage`, sind Administratorberechtigungen für den Cluster erforderlich. Wenn Sie Amazon FSX for NetApp ONTAP mit Astra Trident verwenden, funktioniert der `limitAggregateUsage` Parameter nicht mit den `vsadmin` Benutzerkonten und `fsxadmin`. Der Konfigurationsvorgang schlägt fehl, wenn Sie diesen Parameter angeben.

Es ist zwar möglich, eine restriktivere Rolle in ONTAP zu erstellen, die ein Trident-Treiber verwenden kann, wir empfehlen sie jedoch nicht. Bei den meisten neuen Versionen von Trident sind zusätzliche APIs erforderlich, die berücksichtigt werden müssten, was Upgrades schwierig und fehleranfällig macht.



== Weitere Überlegungen zu NVMe/TCP

Astra Trident unterstützt das Non-Volatile Memory Express (NVMe)-Protokoll über den `ontap-san` folgenden Treiber:

* IPv6
* Snapshots und Klone von NVMe Volumes
* Größe eines NVMe Volumes ändern
* Importieren eines NVMe Volumes, das außerhalb von Astra Trident erstellt wurde, damit sein Lebenszyklus durch Astra Trident gemanagt werden kann
* NVMe-natives Multipathing
* Ordnungsgemäßes oder unzumutbar Herunterfahren der K8s-Nodes (24.06)


Astra Trident unterstützt nicht:

* Dh-HMAC-CHAP, das von nativ von NVMe unterstützt wird
* Multipathing für Device Mapper (DM
* LUKS-Verschlüsselung

