---
sidebar: sidebar 
permalink: trident-install/kubernetes-deploy-operator.html 
keywords: deploy, astra trident, methods, operator, tridentctl, registry, registries 
summary: Sie kĂ¶nnen den Trident-Operator manuell implementieren, um Astra Trident zu installieren. Dieser Prozess gilt fĂĽr Installationen, bei denen die von Astra Trident benĂ¶tigten Container-Images nicht in einer privaten Registrierung gespeichert werden. 
---
= Manuelle Implementierung des Trident-Mitarbeiters (Standard-Modus)
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie kĂ¶nnen den Trident-Operator manuell implementieren, um Astra Trident zu installieren. Dieser Prozess gilt fĂĽr Installationen, bei denen die von Astra Trident benĂ¶tigten Container-Images nicht in einer privaten Registrierung gespeichert werden. Wenn Sie ĂĽber eine private Bildregistrierung verfĂĽgen, verwenden Sie die link:kubernetes-deploy-operator-mirror.html["Prozess fĂĽr Offline-Implementierung"].



== Kritische Informationen zu Astra Trident 24.06

*Sie mĂĽssen die folgenden wichtigen Informationen ĂĽber Astra Trident lesen.*

.<strong> Informationen ĂĽber Astra TripereIT </strong>
[%collapsible%open]
====
* Kubernetes 1.30 wird jetzt in Astra Trident unterstĂĽtzt. Aktualisieren Sie Trident , bevor Sie Kubernetes aktualisieren.
* Astra Trident setzt die Verwendung der Multipathing-Konfiguration in SAN-Umgebungen strikt durch, wobei der empfohlene Wert `find_multipaths: no` in der Multipath.conf Datei verwendet wird.
+
Die Verwendung einer nicht-Multipathing-Konfiguration oder die Verwendung von `find_multipaths: yes` oder `find_multipaths: smart` Wert in der Datei Multipath.conf fĂĽhrt zu Mount-Fehlern. Trident empfiehlt die Verwendung von `find_multipaths: no` seit Version 21.07.



====


== Trident-Operator kann manuell implementiert und Trident installiert werden

ĂśberprĂĽfen Sie link:../trident-install/kubernetes-deploy.html["Die Ăśbersicht ĂĽber die Installation"], um sicherzustellen, dass Sie die Installationsvoraussetzungen erfĂĽllt und die richtige Installationsoption fĂĽr Ihre Umgebung ausgewĂ¤hlt haben.

.Bevor Sie beginnen
Bevor Sie mit der Installation beginnen, melden Sie sich beim Linux-Host an, und ĂĽberprĂĽfen Sie, ob er eine funktionierende verwaltet link:requirements.html["UnterstĂĽtzter Kubernetes-Cluster"^]und dass Sie ĂĽber die erforderliche Privileges verfĂĽgen.


NOTE: Verwenden Sie bei OpenShift `oc` statt `kubectl` in allen folgenden Beispielen, und melden Sie sich zuerst als *System:admin* an, indem Sie oder `oc login -u kube-admin` ausfĂĽhren `oc login -u system:admin`.

[%collapsible%open]
====
. ĂśberprĂĽfen Sie Ihre Kubernetes Version:
+
[listing]
----
kubectl version
----
. ĂśberprĂĽfung der Berechtigungen fĂĽr Cluster-Administratoren:
+
[listing]
----
kubectl auth can-i '*' '*' --all-namespaces
----
. ĂśberprĂĽfen Sie, ob Sie einen Pod starten kĂ¶nnen, der ein Image aus dem Docker Hub verwendet, und ob er das Storage-System ĂĽber das POD-Netzwerk erreichen kann:
+
[listing]
----
kubectl run -i --tty ping --image=busybox --restart=Never --rm -- \
  ping <management IP>
----


====


=== Schritt 1: Laden Sie das Trident Installer-Paket herunter

Das Astra Trident Installationspaket enthĂ¤lt alles, was Sie fĂĽr die Bereitstellung des Trident-Operators und die Installation von Astra Trident benĂ¶tigen. Laden Sie die neueste Version des Trident-Installers herunter und extrahieren Sie sie auslink:https://github.com/NetApp/trident/releases/latest["Die Sektion _Assets_ auf GitHub"^].

[listing]
----
wget https://github.com/NetApp/trident/releases/download/v24.06.0/trident-installer-24.06.0.tar.gz
tar -xf trident-installer-24.06.0.tar.gz
cd trident-installer
----


=== Schritt 2: Erstellen Sie die `TridentOrchestrator` CRD

Erstellen Sie die `TridentOrchestrator` CRD (Custom Resource Definition). Sie erstellen spĂ¤ter eine `TridentOrchestrator` benutzerdefinierte Ressource. Verwenden Sie die entsprechende CRD YAML-Version in `deploy/crds`, um die CRD zu erstellen `TridentOrchestrator`.

[listing]
----
kubectl create -f deploy/crds/trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
----


=== Schritt 3: Implementieren des Trident-Operators

Das Astra Trident-Installationsprogramm stellt eine Paketdatei bereit, mit der der Operator installiert und zugehĂ¶rige Objekte erstellt werden kĂ¶nnen. Die Bundle-Datei ist eine einfache MĂ¶glichkeit, den Operator zu implementieren und Astra Trident mit einer Standardkonfiguration zu installieren.

* Verwenden Sie fĂĽr Cluster mit Kubernetes 1.24 `bundle_pre_1_25.yaml`.
* Verwenden Sie fĂĽr Cluster mit Kubernetes 1.25 oder hĂ¶her `bundle_post_1_25.yaml`.


.Bevor Sie beginnen
* StandardmĂ¤Ăźig stellt das Trident-Installationsprogramm den Operator im Namespace bereit `trident`. Wenn der `trident` Namespace nicht vorhanden ist, erstellen Sie ihn mit:
+
[listing]
----
kubectl apply -f deploy/namespace.yaml
----
* Um den Operator in einem anderen Namespace als dem Namespace bereitzustellen `trident`, aktualisieren Sie `serviceaccount.yaml`, `clusterrolebinding.yaml` und `operator.yaml` erstellen Sie Ihre Bundle-Datei mit dem `kustomization.yaml`.
+
.. Erstellen Sie den `kustomization.yaml` mit dem folgenden Befehl, wobei _<bundle.yaml>_ `bundle_pre_1_25.yaml` `bundle_post_1_25.yaml` auf Ihrer Kubernetes-Version basiert.
+
[listing]
----
cp deploy/kustomization_<bundle.yaml> deploy/kustomization.yaml
----
.. Kompilieren Sie das Bundle mit dem folgenden Befehl, wobei _<bundle.yaml>_ auf Ihrer Kubernetes-Version basiert oder `bundle_post_1_25.yaml` ist `bundle_pre_1_25.yaml`.
+
[listing]
----
kubectl kustomize deploy/ > deploy/<bundle.yaml>
----




.Schritte
. Erstellen Sie die Ressourcen und stellen Sie den Operator bereit:
+
[listing]
----
kubectl create -f deploy/<bundle.yaml>
----
. ĂśberprĂĽfen Sie, ob der Operator, die Bereitstellung und Replikasets erstellt wurden.
+
[listing]
----
kubectl get all -n <operator-namespace>
----



IMPORTANT: Es sollte nur eine Instanz* des Operators in einem Kubernetes-Cluster geben. Erstellen Sie nicht mehrere Implementierungen des Trident-Operators.



=== Schritt 4: Erstellen Sie die `TridentOrchestrator` Trident und installieren Sie sie

Sie kĂ¶nnen jetzt Astra Trident erstellen `TridentOrchestrator` und installieren. Optional kĂ¶nnen Sie link:kubernetes-customize-deploy.html["Anpassung der Trident Installation"]die Attribute in der Spezifikation verwenden `TridentOrchestrator`.

[listing]
----
kubectl create -f deploy/crds/tridentorchestrator_cr.yaml
tridentorchestrator.trident.netapp.io/trident created

kubectl describe torc trident

Name:        trident
Namespace:
Labels:      <none>
Annotations: <none>
API Version: trident.netapp.io/v1
Kind:        TridentOrchestrator
...
Spec:
  Debug:     true
  Namespace: trident
Status:
  Current Installation Params:
    IPv6:                      false
    Autosupport Hostname:
    Autosupport Image:         netapp/trident-autosupport:24.06
    Autosupport Proxy:
    Autosupport Serial Number:
    Debug:                     true
    Image Pull Secrets:
    Image Registry:
    k8sTimeout:           30
    Kubelet Dir:          /var/lib/kubelet
    Log Format:           text
    Silence Autosupport:  false
    Trident Image:        netapp/trident:24.06.0
  Message:                  Trident installed  Namespace:                trident
  Status:                   Installed
  Version:                  v24.06.0
Events:
    Type Reason Age From Message ---- ------ ---- ---- -------Normal
    Installing 74s trident-operator.netapp.io Installing Trident Normal
    Installed 67s trident-operator.netapp.io Trident installed
----


== ĂśberprĂĽfen Sie die Installation

Die Installation kann auf verschiedene Weise ĂĽberprĂĽft werden.



=== Status `TridentOrchestrator` wird verwendet

Der Status von `TridentOrchestrator` gibt an, ob die Installation erfolgreich war, und zeigt die Version von Trident installiert an. WĂ¤hrend der Installation Ă¤ndert sich `Installing` der Status von `TridentOrchestrator` in `Installed`. Wenn Sie den Status beobachten `Failed` und der Bediener nicht in der Lage ist, sich selbst zu erholen, link:../troubleshooting.html["PrĂĽfen Sie die Protokolle"].

[cols="2"]
|===
| Status | Beschreibung 


| Installation | Der Bediener installiert Astra Trident mit diesem `TridentOrchestrator` CR. 


| Installiert | Astra Trident wurde erfolgreich installiert. 


| Deinstallation | Der Operator deinstalliert Astra Trident, weil
`spec.uninstall=true`. 


| Deinstalliert | Astra Trident ist deinstalliert. 


| Fehlgeschlagen | Der Operator konnte Astra Trident nicht installieren, patchen, aktualisieren oder deinstallieren; der Operator versucht automatisch, aus diesem Zustand wiederherzustellen. Wenn dieser Status weiterhin besteht, mĂĽssen Sie eine Fehlerbehebung durchfĂĽhren. 


| Aktualisierung | Der Bediener aktualisiert eine vorhandene Installation. 


| Fehler | Das `TridentOrchestrator` wird nicht verwendet. Eine weitere ist bereits vorhanden. 
|===


=== Den Status der Pod-Erstellung verwenden

ĂśberprĂĽfen Sie den Status der erstellten Pods, ob die Astra Trident-Installation abgeschlossen wurde:

[listing]
----
kubectl get pods -n trident

NAME                                       READY   STATUS    RESTARTS   AGE
trident-controller-7d466bf5c7-v4cpw        6/6     Running   0           1m
trident-node-linux-mr6zc                   2/2     Running   0           1m
trident-node-linux-xrp7w                   2/2     Running   0           1m
trident-node-linux-zh2jt                   2/2     Running   0           1m
trident-operator-766f7b8658-ldzsv          1/1     Running   0           3m
----


=== Verwenden `tridentctl`

Mit kĂ¶nnen Sie `tridentctl` die installierte Version von Astra Trident ĂĽberprĂĽfen.

[listing]
----
./tridentctl -n trident version

+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 24.06.0        | 24.06.0        |
+----------------+----------------+
----